# This application does not use a database.
# Using the nulldb adapter to satisfy Rails' database requirements without actually connecting to a database.

default: &default
  adapter: nulldb

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
